apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  database-user: {{ .Values.database.user | quote }}
  database-password: {{ .Values.database.password | default "CHANGE_ME" | quote }}
