database:
    user: ENC[AES256_GCM,data:zb8E1shv/OY=,iv:H0sJ5AOzLY1s16opM3LtubNlu8xeGXd/39E9y2ttNZ8=,tag:CWdDjqOdcHXOalEH4cfPhQ==,type:str]
    password: ENC[AES256_GCM,data:A9tfte+2JEc=,iv:gVaaU5xLLT+gNF2JgYxJoxPln5H/Cs7a9TMth0Dzx0k=,tag:YumEPZF+QXKgeNukIPJvVw==,type:str]
sops:
    age:
        - recipient: age137rtm8kntflh674xdy3vfjdwgpq4ddlhpydtsxvv3zmpdep6lqxq2c0stp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza0Q1ZWVkMVlMb3hxeFVt
            bzBHSm5CSTFtdGhSMUZZdmhpREhMcjV0OGhNCnhxelJ1b2RDY01jREQ1NmNZZ1Bl
            dnJjS2gyL3ZTOFEyVXBDdE9BaWMyazQKLS0tIGlReVpURUE4ZHZtM1ZFTjhiWlZ6
            RlpJWWZsSGJMWUszemQ5b2t6UE5rQ00KlFZ7k4Hi5tgy/7quIAghtNcYJSLT5QZd
            KEJO0T9HoorXiKTuBNsxd3rzfCgifMKebPrKPIrw0pZ4pNgSi/siZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T23:52:33Z"
    mac: ENC[AES256_GCM,data:O7utnqWNRTLkMatsj/evSSK13C4/RehLHtPYqbNHNyc/dDrN+YqKvSSGkEgqDxaCYiajgDriR+9ESIK2we0/I2rgo2rerZTOuJeBEwa5CuVJn0yXcbmwsmibo2JYw2b2JnySYfx+IKcXed58cTC6Dk0R3vP3jjLb6pxT33QNz4E=,iv:kVI7Phk+rSGNi6wFtT2alwVGuZjJp6JY90IB2UOiOqY=,tag:FBUQCA4l0Yp/6w7W8Ys2ng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
